services:
  ultipro.authentication:
    class: Ultipro\Authentication
    arguments:
      - '%ultipro_sdk.username%'
      - '%ultipro_sdk.password%'
      - '%ultipro_sdk.customer_api_key%'
      - '%ultipro_sdk.user_api_key%'

  Ultipro\Authentication:
    alias: 'ultipro.authentication'

  ultipro.soap.client:
    class: Ultipro\UltiproSoapClient
    arguments:
      - '@ultipro.authentication'
      - 'https://service5.ultipro.com/services/BIDataService'
      - '%ultipro_sdk.options%'
      - '@logger'

  Ultipro\UltiproSoapClient:
    alias: 'ultipro.soap.client'

  ultipro.client:
    class: Ultipro\UltiproClient
    arguments:
      - '@ultipro.authentication'
      - '%ultipro_sdk.base_uri%'
      - '%ultipro_sdk.options%'

  Ultipro\Client:
    alias: 'ultipro.client'

  ultipro.client.configuration:
    class: Ultipro\Configuration\ConfigurationClient
    parent: ultipro.client

  Ultipro\Configuration\ConfigurationClient:
    alias: 'ultipro.client.configuration'

  ultipro.client.personnel:
    class: Ultipro\Personnel\PersonnelClient
    parent: ultipro.client

  Ultipro\Personnel\PersonnelClient:
     alias: 'ultipro.client.personnel'

  ultipro.client.report:
    class: Ultipro\ReportsAsService\ReportClient
    parent: ultipro.soap.client

  Ultipro\ReportsAsService\ReportClient:
    alias: 'ultipro.client.report'